/**
 * The agent payload published inside the npm package:
 *
 *   agent/
 *   ├── AGENTS.md                        (hand-written, committed)
 *   └── skills/velojs-<slug>/SKILL.md    (generated from site/docs/*.md)
 *
 * The skills are gitignored and regenerated by the `prepack` hook, which npm
 * runs on every `npm pack` and `npm publish` — there is no path that produces a
 * tarball without it. So nothing derived lives in git and drift is impossible
 * by construction rather than by a test. What is left to check is the *shape*:
 * these tests run the generator in memory and assert what it emits.
 *
 * The YAML is validated with a real parser (`yaml`), never with the repo's own
 * hand-rolled one: that parser is deliberately tolerant, so checking our output
 * with it would prove we are self-consistent, not that we are correct. A
 * SKILL.md whose frontmatter does not parse fails silently — the skill simply
 * never loads.
 */
import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { parse as parseYaml } from "yaml";
import { buildSkills, DOCS_DIR } from "../scripts/build-skills.js";
import { readDocs } from "../scripts/docs-frontmatter.js";

const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** The frontmatter block of a SKILL.md / doc, parsed with a real YAML reader. */
function frontmatterOf(content: string): Record<string, unknown> {
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (!match) throw new Error("no frontmatter block");
    return parseYaml(match[1]!) ?? {};
}

describe("site/docs frontmatter", () => {
    const docs = readDocs(DOCS_DIR);

    it("finds the docs", () => {
        expect(docs.length).toBeGreaterThan(0);
    });

    it("every doc declares a description — without it the skill never loads", () => {
        const missing = docs.filter((d) => !d.frontmatter.description).map((d) => d.filename);
        expect(missing).toEqual([]);
    });

    it("every doc's frontmatter is valid YAML carrying only `description`", () => {
        for (const doc of docs) {
            const raw = fs.readFileSync(path.join(DOCS_DIR, doc.filename), "utf-8");
            const fm = frontmatterOf(raw);
            expect(Object.keys(fm), doc.filename).toEqual(["description"]);
            expect(typeof fm.description, doc.filename).toBe("string");
        }
    });

    it("description fits the 1–1024 char limit both harnesses impose", () => {
        for (const doc of docs) {
            const len = doc.frontmatter.description!.length;
            expect(len, doc.filename).toBeGreaterThan(0);
            expect(len, doc.filename).toBeLessThanOrEqual(1024);
        }
    });

    it("the body no longer carries the frontmatter", () => {
        for (const doc of docs) {
            expect(doc.body.startsWith("---"), doc.filename).toBe(false);
            expect(doc.body.trimStart().startsWith("# "), doc.filename).toBe(true);
        }
    });
});

describe("agent/skills", () => {
    const skills = buildSkills(DOCS_DIR);

    it("emits one skill per doc", () => {
        expect(skills.length).toBe(readDocs(DOCS_DIR).length);
    });

    it("refuses to build a doc with no description — prepack must fail, not ship it", () => {
        // The generator is the release gate: a description-less doc would produce
        // a skill the model never loads, which is invisible once published. This
        // throw is what turns that into a failed `npm pack`.
        const empty = fs.mkdtempSync(path.join(fs.realpathSync("/tmp"), "velo-docs-"));
        try {
            fs.writeFileSync(path.join(empty, "01-nope.md"), "# Nope\n\nno frontmatter here\n");
            expect(() => buildSkills(empty)).toThrow(/description/i);
        } finally {
            fs.rmSync(empty, { recursive: true, force: true });
        }
    });

    it("names the directory exactly what the frontmatter declares", () => {
        for (const skill of skills) {
            const fm = frontmatterOf(skill.content);
            expect(fm.name, skill.relPath).toBe(skill.name);
            expect(skill.relPath.split("/")[0], skill.relPath).toBe(skill.name);
        }
    });

    it("uses kebab-case names prefixed with the package", () => {
        for (const skill of skills) {
            expect(NAME_RE.test(skill.name), skill.name).toBe(true);
            expect(skill.name.startsWith("velojs-"), skill.name).toBe(true);
        }
    });

    it("emits only `name` and `description` — opencode drops any other field", () => {
        for (const skill of skills) {
            const fm = frontmatterOf(skill.content);
            expect(Object.keys(fm).sort(), skill.relPath).toEqual(["description", "name"]);
        }
    });

    it("keeps the doc body intact after the frontmatter", () => {
        const docs = readDocs(DOCS_DIR);
        for (const skill of skills) {
            const doc = docs.find((d) => `velojs-${d.slug}` === skill.name)!;
            const body = skill.content.replace(/^---\r?\n[\s\S]*?\r?\n---\r?\n\r?\n/, "");
            expect(body, skill.relPath).toBe(doc.body);
        }
    });
});

describe("npm package", () => {
    const pkg = JSON.parse(
        fs.readFileSync(new URL("../package.json", import.meta.url), "utf-8"),
    ) as { files: string[] };

    it("ships agent/ — agent-sync reads it from node_modules", () => {
        expect(pkg.files).toContain("agent/");
    });
});
